"""
ML-Enhanced Backtester Module
Filters trades using ML model predictions.
"""

import pandas as pd
import numpy as np
from typing import Optional

from config import ML_CONFIDENCE_THRESHOLD, RESULTS_DIR, PLOTS_DIR
from strategy import EMAStrategy, run_strategy
from backtester import calculate_metrics, plot_equity_curve, generate_backtest_report
from ml_models import XGBoostPredictor, LSTMPredictor


def run_ml_enhanced_backtest(
    df: pd.DataFrame,
    xgb_model: Optional[XGBoostPredictor] = None,
    lstm_model: Optional[LSTMPredictor] = None,
    confidence_threshold: float = ML_CONFIDENCE_THRESHOLD
):
    """
    Run backtest with ML filter - only take trades when model predicts profitable.
    
    Args:
        df: DataFrame with features
        xgb_model: Trained XGBoost model
        lstm_model: Trained LSTM model
        confidence_threshold: Minimum probability to take trade
    
    Returns:
        Dictionary with results for baseline, XGBoost-filtered, and LSTM-filtered strategies
    """
    print("=" * 60)
    print("ML-ENHANCED BACKTESTING")
    print("=" * 60)
    
    results = {}
    
    # 1. Baseline strategy (no ML filter)
    print("\n--- Baseline Strategy ---")
    baseline_results, baseline_trades, strategy = run_strategy(df, use_regime_filter=True)
    
    if len(baseline_trades) == 0:
        print("No trades generated by baseline strategy.")
        return results
    
    baseline_equity = baseline_results['cumulative_pnl'] + 100000
    baseline_metrics = calculate_metrics(baseline_trades, baseline_equity)
    
    results['baseline'] = {
        'results': baseline_results,
        'trades': baseline_trades,
        'metrics': baseline_metrics
    }
    
    print(f"  Total trades: {len(baseline_trades)}")
    print(f"  Total return: {baseline_metrics['total_return']:.2f} pts")
    print(f"  Sharpe ratio: {baseline_metrics['sharpe_ratio']:.3f}")
    
    # 2. XGBoost-filtered strategy
    if xgb_model is not None and xgb_model.model is not None:
        print("\n--- XGBoost-Filtered Strategy ---")
        xgb_trades = _filter_trades_with_model(
            df, baseline_trades, xgb_model, confidence_threshold, model_type='xgboost'
        )
        
        if len(xgb_trades) > 0:
            # Recalculate equity curve for filtered trades
            xgb_results = _recalculate_results(df, xgb_trades)
            xgb_equity = xgb_results['cumulative_pnl'] + 100000
            xgb_metrics = calculate_metrics(xgb_trades, xgb_equity)
            
            results['xgboost'] = {
                'results': xgb_results,
                'trades': xgb_trades,
                'metrics': xgb_metrics
            }
            
            print(f"  Total trades: {len(xgb_trades)} (filtered from {len(baseline_trades)})")
            print(f"  Total return: {xgb_metrics['total_return']:.2f} pts")
            print(f"  Sharpe ratio: {xgb_metrics['sharpe_ratio']:.3f}")
        else:
            print("  No trades passed XGBoost filter.")
    
    # 3. LSTM-filtered strategy
    if lstm_model is not None and lstm_model.model is not None:
        print("\n--- LSTM-Filtered Strategy ---")
        lstm_trades = _filter_trades_with_model(
            df, baseline_trades, lstm_model, confidence_threshold, model_type='lstm'
        )
        
        if len(lstm_trades) > 0:
            lstm_results = _recalculate_results(df, lstm_trades)
            lstm_equity = lstm_results['cumulative_pnl'] + 100000
            lstm_metrics = calculate_metrics(lstm_trades, lstm_equity)
            
            results['lstm'] = {
                'results': lstm_results,
                'trades': lstm_trades,
                'metrics': lstm_metrics
            }
            
            print(f"  Total trades: {len(lstm_trades)} (filtered from {len(baseline_trades)})")
            print(f"  Total return: {lstm_metrics['total_return']:.2f} pts")
            print(f"  Sharpe ratio: {lstm_metrics['sharpe_ratio']:.3f}")
        else:
            print("  No trades passed LSTM filter.")
    
    # Generate comparison
    _generate_comparison_report(results)
    
    return results


def _filter_trades_with_model(
    df: pd.DataFrame,
    trades_df: pd.DataFrame,
    model,
    threshold: float,
    model_type: str = 'xgboost'
) -> pd.DataFrame:
    """
    Filter trades using ML model predictions.
    """
    filtered_trades = []
    df_reset = df.reset_index(drop=True)
    
    for _, trade in trades_df.iterrows():
        entry_time = trade['entry_time']
        
        # Find candle index
        candle_mask = df_reset['datetime'] == entry_time
        if not candle_mask.any():
            continue
        
        candle_idx = df_reset[candle_mask].index[0]
        
        if model_type == 'xgboost':
            # Get features for XGBoost
            if candle_idx > 0:
                feature_cols = model.feature_columns
                feature_cols = [c for c in feature_cols if c in df_reset.columns]
                X = df_reset.loc[candle_idx - 1, feature_cols].values.reshape(1, -1)
                
                try:
                    prob = model.predict_proba(X)[0]
                    if prob >= threshold:
                        trade_copy = trade.copy()
                        trade_copy['ml_confidence'] = prob
                        filtered_trades.append(trade_copy)
                except Exception as e:
                    pass
        
        elif model_type == 'lstm':
            # Get sequence for LSTM
            seq_len = model.sequence_length
            if candle_idx >= seq_len:
                feature_cols = model.feature_columns
                feature_cols = [c for c in feature_cols if c in df_reset.columns]
                X = df_reset.loc[candle_idx - seq_len:candle_idx - 1, feature_cols].values
                X = X.reshape(1, seq_len, len(feature_cols))
                
                try:
                    prob = model.predict_proba(X)[0]
                    if prob >= threshold:
                        trade_copy = trade.copy()
                        trade_copy['ml_confidence'] = prob
                        filtered_trades.append(trade_copy)
                except Exception as e:
                    pass
    
    return pd.DataFrame(filtered_trades)


def _recalculate_results(df: pd.DataFrame, trades_df: pd.DataFrame) -> pd.DataFrame:
    """
    Recalculate trading results for filtered trades.
    """
    results = df[['datetime', 'spot_close']].copy()
    results['trade_pnl'] = 0.0
    
    for _, trade in trades_df.iterrows():
        exit_time = trade['exit_time']
        pnl = trade['pnl']
        
        mask = results['datetime'] == exit_time
        if mask.any():
            results.loc[mask, 'trade_pnl'] = pnl
    
    results['cumulative_pnl'] = results['trade_pnl'].cumsum()
    
    return results


def _generate_comparison_report(results: dict):
    """
    Generate comparison report between strategies.
    """
    print("\n" + "=" * 60)
    print("STRATEGY COMPARISON")
    print("=" * 60)
    
    # Create comparison table
    comparison_data = []
    
    for strategy_name in ['baseline', 'xgboost', 'lstm']:
        if strategy_name in results:
            metrics = results[strategy_name]['metrics']
            trades = results[strategy_name]['trades']
            
            comparison_data.append({
                'Strategy': strategy_name.upper(),
                'Total Trades': len(trades),
                'Total Return': f"{metrics['total_return']:.2f}",
                'Win Rate': f"{metrics['win_rate']:.1f}%",
                'Sharpe': f"{metrics['sharpe_ratio']:.3f}",
                'Max DD': f"{metrics['max_drawdown_pct']:.1f}%",
                'Profit Factor': f"{metrics['profit_factor']:.2f}"
            })
    
    comparison_df = pd.DataFrame(comparison_data)
    print("\n" + comparison_df.to_string(index=False))
    
    # Save comparison
    comparison_df.to_csv(RESULTS_DIR / "strategy_comparison.csv", index=False)
    print(f"\nâœ“ Saved comparison to {RESULTS_DIR / 'strategy_comparison.csv'}")
    
    print("\n" + "=" * 60)
